### ISSUE TITLE
why is the 'generator' handled as a script?

### ISSUE THREAD

**Issue by benkb** [libguestfs/libnbd#1]
Hi
I'm not questioning your decision, in contrary I was often surprised why not more people using this feature, especially when dealing with simpler scripting-like task.
But here it seems that you choose to handle a fairly complex program as script and with that decision comes a certain runtime performance penalty.
So why did you choose this form over a the compiled options?
Thanks
Ben

**Comment by rwmjones** [comment]
It's only slow the first time it is run, and that's because it has to run (Perl) pod2text.  After that it caches the output in `generator/generator-cache.v1` and it should run very quickly.  On my laptop:
```
$ time generator/generator 

real	0m0.570s
user	0m0.537s
sys	0m0.032s
```
We could compile the generator, since OCaml supports high performance native code, but I doubt that the time taken to compile the generator and run it would be any less.  (The generator shouldn't run unless a generated file needs to be rebuilt, that is assuming I got the dependencies right).

**Comment by benkb** [comment]
thanks! Interesting bit about pod2text ... maybe that would be a nice project to do in (scripted) OCaml as well :-)
